// TerraForgeDualContour.h
// TerraForge — Dual Contouring mesh generation from voxel data.
// Produces smooth terrain with sharp mine-wall edges.
// Thread-safe: operates on chunk snapshots, outputs to FTerraChunkMeshData.

#pragma once

#include "CoreMinimal.h"
#include "TerraForgeTypes.h"

class FTerraForgeChunk;

/**
 * Dual Contouring mesh generator.
 *
 * Unlike Marching Cubes (rounded blobs), Dual Contouring places one vertex
 * per voxel cell using a QEF (Quadratic Error Function) solve. This preserves
 * sharp edges (mine walls, cliff faces) while still producing smooth natural
 * terrain where appropriate.
 *
 * All methods are static and thread-safe — no shared mutable state.
 */
class FTerraForgeDualContour
{
public:
	/**
	 * Generate a mesh from a chunk's voxel data.
	 *
	 * @param Chunk       The chunk to generate mesh for (read-only snapshot).
	 * @param LOD         Level of detail (controls vertex density).
	 * @param OutMesh     Output mesh data (vertices, triangles, normals, etc.).
	 */
	static void GenerateMesh(
		const FTerraForgeChunk& Chunk,
		EChunkLOD LOD,
		FTerraChunkMeshData& OutMesh);

	/**
	 * Generate a simplified collision mesh (fewer triangles than visual mesh).
	 *
	 * @param Chunk       The chunk to generate collision for.
	 * @param OutMesh     Output mesh data for collision.
	 */
	static void GenerateCollisionMesh(
		const FTerraForgeChunk& Chunk,
		FTerraChunkMeshData& OutMesh);

private:
	// ── Internal types ──────────────────────────────────────────────────────

	/** Surface crossing on a voxel grid edge. */
	struct FEdgeCrossing
	{
		FVector Position;    // World position of the surface crossing
		FVector Normal;      // Surface normal at crossing
		uint8   Material;    // Material of the solid side
	};

	/** QEF data accumulator for one cell. */
	struct FQEFData
	{
		// Normal matrix (A^T A) — symmetric 3x3
		float ATA[6] = {};  // Upper triangle: [xx, xy, xz, yy, yz, zz]
		// Right-hand side (A^T b)
		FVector ATb = FVector::ZeroVector;
		// Mass point (average of all crossing positions)
		FVector MassPoint = FVector::ZeroVector;
		int32 NumCrossings = 0;

		void AddPlane(const FVector& Point, const FVector& Normal);
		FVector Solve(const FVector& CellMin, const FVector& CellMax) const;
	};

	/** Vertex generated by DC for one cell. */
	struct FDCVertex
	{
		FVector  Position;
		FVector  Normal;
		uint8    Material;
		bool     bValid = false;
	};

	// ── Core algorithm steps ────────────────────────────────────────────────

	/** Find surface crossing on an edge between two voxels. */
	static bool FindEdgeCrossing(
		const FTerraForgeChunk& Chunk,
		int32 X0, int32 Y0, int32 Z0,
		int32 X1, int32 Y1, int32 Z1,
		FEdgeCrossing& OutCrossing);

	/** Solve QEF for a single cell to find optimal vertex position. */
	static FDCVertex SolveCell(
		const FTerraForgeChunk& Chunk,
		int32 CellX, int32 CellY, int32 CellZ,
		int32 Step);

	/** Emit a quad connecting 4 cell vertices along a sign-change edge. */
	static void EmitQuad(
		const FDCVertex& V0, const FDCVertex& V1,
		const FDCVertex& V2, const FDCVertex& V3,
		bool bFlip,
		FTerraChunkMeshData& OutMesh);

	/** Compute smooth vertex normal from surrounding cell normals. */
	static FVector ComputeSmoothNormal(
		const FDCVertex* CellVertices,
		int32 SizeX, int32 SizeY, int32 SizeZ,
		int32 CX, int32 CY, int32 CZ);

	/** Calculate UV coordinates for a vertex based on position and normal. */
	static FVector2D CalculateUV(const FVector& Position, const FVector& Normal);

	/** Get vertex color from geological material (for shader blending). */
	static FColor MaterialToVertexColor(uint8 Material);

	/** LOD step size. Full=1, Half=2, Quarter=4, Minimal=8. */
	static int32 GetLODStep(EChunkLOD LOD);
};
